[project]
name = "deep-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-google-genai>=3.0.0",
    "langgraph>=1.0.1",
    "tavily-python>=0.7.12",
    "deepagents"
]
